apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mapcache
  name: mapcache
spec:
  ports:
  - name: "1337"
    port: 1337
    targetPort: 1337
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    io.kompose.service: mapcache
status:
  loadBalancer: {}
