apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mapcache
  name: mapcache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mapcache
    spec:
      containers:
      - image: mapcentia/mapcache
        name: mapcache
        resources: {}
        volumeMounts:
        - mountPath: /var/www/geocloud2/app/wms
          name: gc2core-var-www-geocloud2-app-wms
        - mountPath: /etc/apache2/sites-enabled
          name: mapcache-etc-apache2-sites-enabled
      restartPolicy: Always
      volumes:
      - name: gc2core-var-www-geocloud2-app-wms
        azureFile:
          secretName: storage-secret
          shareName: gc2core-var-www-geocloud2-app-wms
      - name: mapcache-etc-apache2-sites-enabled
        azureFile:
          secretName: storage-secret
          shareName: mapcache-etc-apache2-sites-enabled
status: {}
