apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pgbouncer
  name: pgbouncer
spec:
  containers:
  - image: PGBOUNCER_IMAGE
    name: pgbouncer
    ports:
    - containerPort: 5433
    resources: {}
  restartPolicy: OnFailure
status: {}
