apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: postgis
  name: postgis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgis
    spec:
      containers:
      - env:
        - name: GC2_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: GC2_PASSWORD
              name: postgis-gc2-env
        - name: LOCALE
          valueFrom:
            configMapKeyRef:
              key: LOCALE
              name: postgis-gc2-env
        - name: TIMEZONE
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: postgis-gc2-env
        image: mapcentia/postgis
        name: postgis
        resources: {}
        ports:
        - containerPort: 5432
      restartPolicy: Always
status: {}
