apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
data:
  azurestorageaccountname: c2FzaHVr
  azurestorageaccountkey: UWc1RFdTRzNKNi9YQjVUQ1RjMWVJbUtmenpnUGgrOU9XRWZsaEcvTlUyVzhzam9WTERwTTBVSHBEb3QxQWpKQjBvUzJzTmRybGw0c3YxY2N4NHpWTnc9PQ==