apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: gc2core
  name: gc2core
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gc2core
    spec:
      containers:
      - image: alexshumilov/gc2core:latest
        name: gc2core
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/www/geocloud2/app/wms/mapcache
          name: gc2core-var-www-geocloud2-app-wms-mapcache
        - mountPath: /var/lib/php/sessions
          name: gc2core-var-lib-php-sessions
        - mountPath: /var/www/geocloud2/app/tmp
          name: gc2core-var-www-geocloud2-app-tmp
        ports:
        - containerPort: 80
        env:
        - name: GC2_HOST
          valueFrom:
            configMapKeyRef:
              key: GC2_HOST
              name: gc2core-env
        - name: GC2_DATABASE
          valueFrom:
            configMapKeyRef:
              key: GC2_DATABASE
              name: gc2core-env
        - name: GC2_PORT
          valueFrom:
            configMapKeyRef:
              key: GC2_PORT
              name: gc2core-env
        - name: GC2_USER
          valueFrom:
            configMapKeyRef:
              key: GC2_USER
              name: gc2core-env
        - name: GC2_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: GC2_PASSWORD
              name: gc2core-env
        - name: GC2_BOUNCER
          valueFrom:
            configMapKeyRef:
              key: GC2_BOUNCER
              name: gc2core-env
        - name: VIDI_URL
          valueFrom:
            configMapKeyRef:
              key: VIDI_URL
              name: gc2core-env
        - name: GOOGLE_API_KEY
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_API_KEY
              name: gc2core-env
      restartPolicy: Always
      volumes:
      - name: gc2core-var-www-geocloud2-app-wms-mapcache
        azureFile:
          secretName: storage-secret
          shareName: gc2core-var-www-geocloud2-app-wms-mapcache
      - name: gc2core-var-lib-php-sessions
        azureFile:
          secretName: storage-secret
          shareName: gc2core-var-lib-php-sessions
      - name: gc2core-var-www-geocloud2-app-tmp
        azureFile:
          secretName: storage-secret
          shareName: gc2core-var-www-geocloud2-app-tmp
status: {}
