apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: pgbouncer
  name: pgbouncer
spec:
  ports:
  - name: "5433"
    port: 5433
    targetPort: 5433
  selector:
    io.kompose.service: pgbouncer
status:
  loadBalancer: {}
