apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: vidi
  name: vidi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vidi
    spec:
      containers:
      - env:
        - name: GC2_HOST
          valueFrom:
            configMapKeyRef:
              key: GC2_HOST
              name: vidi-env
        image: mapcentia/vidi
        name: vidi
        resources: {}
        volumeMounts:
        - mountPath: /root/vidi/public/tmp
          name: vidi-root-vidi-public-tmp
        - mountPath: /tmp/sessions
          name: vidi-tmp-sessions
      restartPolicy: Always
      volumes:
      - name: vidi-root-vidi-public-tmp
        azureFile:
          secretName: storage-secret
          shareName: vidi-root-vidi-public-tmp
      - name: vidi-tmp-sessions
        azureFile:
          secretName: storage-secret
          shareName: vidi-tmp-sessions
status: {}
